# Generated by Django 3.0.4 on 2020-03-22 12:12

from django.db import migrations, models
import django.db.models.deletion
import student.models
import student.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Degree')),
            ],
            options={
                'unique_together': {('name', 'degree')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=student.models.student_image_upload)),
                ('euid', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('address', models.CharField(max_length=255)),
                ('race', models.CharField(choices=[('AA', 'African American'), ('NA', 'Native American'), ('PI', 'Pacific Islander'), ('AS', 'Asian'), ('NH', 'Native Hawaiian')], max_length=2)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('application_date', models.DateField()),
                ('application_status', models.CharField(choices=[('A', 'Active'), ('IA', 'Inactive')], max_length=2)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Advisor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Program')),
            ],
        ),
    ]
