# Generated by Django 3.0.4 on 2020-03-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200322_1223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('name', 'degree')},
        ),
    ]
