# Generated by Django 3.0.4 on 2020-03-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200322_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='NP', max_length=20),
            preserve_default=False,
        ),
    ]
