# Generated by Django 3.0.4 on 2020-03-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200323_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='remarks',
        ),
    ]
