# Generated by Django 3.0.4 on 2020-03-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200323_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField()),
                ('position', models.CharField(max_length=255)),
                ('hire_type', models.CharField(max_length=255)),
                ('pay_level', models.CharField(max_length=255)),
                ('funding_source', models.CharField(max_length=255)),
                ('assignment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='EducationHistoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gpa', models.CharField(max_length=4)),
                ('education_level', models.CharField(choices=[('B', 'Bachelors'), ('M', 'Masters'), ('P', 'PHD')], max_length=1)),
                ('research_professor', models.CharField(max_length=255)),
                ('milestone', models.CharField(max_length=255)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.University')),
            ],
        ),
    ]
