# Generated by Django 3.0.4 on 2020-03-23 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0011_educationhistoy_employmenthistory_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_history',
            field=models.ManyToManyField(to='student.EducationHistoy'),
        ),
        migrations.AddField(
            model_name='student',
            name='employment_history',
            field=models.ManyToManyField(to='student.EmploymentHistory'),
        ),
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='files',
            field=models.ManyToManyField(to='student.StudentFile'),
        ),
    ]
