# Generated by Django 3.0.4 on 2020-03-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200323_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationhistoy',
            name='milestone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educationhistoy',
            name='research_professor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
