# Generated by Django 3.0.4 on 2020-03-23 15:41

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20200323_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='file_link',
            field=models.FileField(upload_to=student.models.upload_student_files),
        ),
    ]
