# Generated by Django 3.0.4 on 2020-04-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20200406_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_academic_level',
        ),
    ]
