# Generated by Django 3.0.4 on 2020-04-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20200406_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationhistoy',
            name='end_date',
            field=models.CharField(max_length=255),
        ),
    ]
