# Generated by Django 3.0.4 on 2020-04-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20200406_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='assignment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='funding_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='pay_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
