# Generated by Django 3.0.4 on 2020-04-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20200406_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gre_total_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='greq_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='greva_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sat_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
