# Generated by Django 3.0.4 on 2020-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20200406_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tofel_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
