# Generated by Django 3.0.4 on 2020-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_student_tofel_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='greva_score',
            new_name='grea_score',
        ),
        migrations.AddField(
            model_name='student',
            name='grev_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
