# Generated by Django 3.0.5 on 2020-04-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20200416_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationhistoy',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='educationhistoy',
            name='research_professor',
        ),
    ]
