# Generated by Django 2.2.5 on 2020-02-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gre_a', models.CharField(max_length=10)),
                ('gre_q', models.CharField(max_length=10)),
                ('gre_v', models.CharField(max_length=10)),
                ('gre_total', models.CharField(max_length=10)),
                ('ms_major', models.CharField(max_length=100)),
                ('ms_university', models.CharField(max_length=200)),
                ('ms_year', models.CharField(max_length=10)),
                ('ms_country', models.CharField(max_length=50)),
                ('ms_gpa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=5000)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=10)),
                ('euid', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('race', models.CharField(max_length=20)),
                ('immigration', models.CharField(max_length=50)),
                ('address_line', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('adviser', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('degree_level', models.CharField(max_length=50)),
                ('app_status', models.CharField(max_length=50)),
                ('app_received_date', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=10000)),
                ('files', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Undergrad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toefl', models.CharField(max_length=10)),
                ('sat_reading', models.CharField(max_length=10)),
                ('sat_writing', models.CharField(max_length=10)),
                ('sat_math', models.CharField(max_length=10)),
                ('sat_total', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=100)),
                ('minor', models.CharField(max_length=100)),
                ('ba_university', models.CharField(max_length=200)),
                ('ba_year', models.CharField(max_length=20)),
                ('ba_country', models.CharField(max_length=50)),
                ('ba_gpa', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Phd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd_major', models.CharField(max_length=100)),
                ('research_professor', models.CharField(max_length=100)),
                ('milestone', models.CharField(max_length=10000)),
                ('evaluation', models.CharField(max_length=10000)),
                ('masters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Masters')),
            ],
        ),
        migrations.AddField(
            model_name='masters',
            name='undergrad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Undergrad'),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('hire_type', models.CharField(max_length=100)),
                ('pay_level', models.CharField(max_length=100)),
                ('funding_source', models.CharField(max_length=200)),
                ('assignment', models.CharField(max_length=1000)),
                ('employment_history', models.CharField(max_length=2500)),
                ('undergrad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Undergrad')),
            ],
        ),
    ]
