# Generated by Django 2.2.5 on 2020-02-22 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='undergrad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Student'),
        ),
    ]
