# Generated by Django 2.2.5 on 2020-02-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200222_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='undergrad',
            new_name='student',
        ),
    ]
