# Generated by Django 2.2.5 on 2020-02-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200222_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masters',
            name='undergrad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Student'),
        ),
        migrations.AlterField(
            model_name='phd',
            name='masters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.CharField(max_length=50000),
        ),
    ]
