# Generated by Django 3.0.4 on 2020-04-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20200406_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='nationality',
            new_name='citizenship',
        ),
    ]
